---
MXNET_VERSION: "mxnet"
output_path: "./search/RoITransformer_DOTA/output/rcnn/DOTA"
symbol: resnet_v1_101_rcnn_light_head
gpus: '0'
CLASS_AGNOSTIC: false
SCALES:
- 1024
- 1024
#- 600
#- 1000
#TEST_SCALES: [[1024, 1024], [512, 512]]
default:
  frequent: 100
  kvstore: device
network:
  pretrained: "./search/RoITransformer_DOTA/model/pretrained_model/resnet_v1_101"
  pretrained_epoch: 0
  PIXEL_MEANS:
  - 103.06
  - 115.90
  - 123.15
  IMAGE_STRIDE: 0
  RCNN_FEAT_STRIDE: 16
  RPN_FEAT_STRIDE: 16
  FIXED_PARAMS:
  - conv1
  - bn_conv1
  - res2
  - bn2
  - gamma
  - beta
  FIXED_PARAMS_SHARED:
  - conv1
  - bn_conv1
  - res2
  - bn2
  - res3
  - bn3
  - res4
  - bn4
  - gamma
  - beta
  ANCHOR_RATIOS:
  - 0.5
  - 1
  - 2
  ANCHOR_SCALES:
  - 4
  - 8
  - 16
  - 32
  - 64
#  NUM_ANCHORS: 12
  NUM_ANCHORS: 15
  RRoI_REGRESSION: false
dataset:
  NUM_CLASSES: 16
  dataset: DOTA_oriented_v2
#  dataset_path: "./data/coco"
  dataset_path: "./media"
  image_set: train
  root_path: "./media"
  test_image_set: test
  proposal: rpn
TRAIN:
#  lr: 0.000125
  lr: 0.0005
  lr_step: '30,40'
  warmup: true
  warmup_lr: 0.00005
  # typically we will use 8000 warmup step for single GPU for COCO
  warmup_step: 1000
  begin_epoch: 0
  end_epoch: 40
  # for debug
  model_prefix: 'rcnn_dota'
  # whether resume training
  RESUME: false
  # whether flip image
  FLIP: false
  # whether shuffle image
  SHUFFLE: true
  # whether use OHEM
  ENABLE_OHEM: false
  # size of images for each device, 2 for rcnn, 1 for rpn and e2e
  BATCH_IMAGES: 1
  # e2e changes behavior of anchor loader and metric
  END2END: true
  # group images with similar aspect ratio
  ASPECT_GROUPING: true
  # R-CNN
  # rcnn rois batch size
#  BATCH_ROIS: 256
  BATCH_ROIS: 512
  BATCH_ROIS_OHEM: 128
#  BATCH_ROIS: -1
#  BATCH_ROIS_OHEM: 512
  # rcnn rois sampling params
#  FG_FRACTION: 0.25
  FG_FRACTION: 0.5
  FG_THRESH: 0.5
  BG_THRESH_HI: 0.5
  BG_THRESH_LO: 0.0
  # rcnn bounding box regression params
  BBOX_REGRESSION_THRESH: 0.5
  BBOX_WEIGHTS:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0

  # RPN anchor loader
  # rpn anchors batch size
#  RPN_BATCH_SIZE: 256
  RPN_BATCH_SIZE: 512

  # rpn anchors sampling params
  RPN_FG_FRACTION: 0.5
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_NEGATIVE_OVERLAP: 0.3
  RPN_CLOBBER_POSITIVES: false
  # rpn bounding box regression params
  RPN_BBOX_WEIGHTS:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  RPN_POSITIVE_WEIGHT: -1.0
  # used for end2end training
  # RPN proposal
  CXX_PROPOSAL: true
  RPN_NMS_THRESH: 0.7
#  RPN_PRE_NMS_TOP_N: 12000
#  RPN_POST_NMS_TOP_N: 2000
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 800
  RPN_MIN_SIZE: 10
  # approximate bounding box regression
  BBOX_NORMALIZATION_PRECOMPUTED: true
  BBOX_MEANS:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  BBOX_STDS:
  - 0.1
  - 0.1
  - 0.2
  - 0.2
  - 0.05
TEST:
  # use rpn to generate proposal
  HAS_RPN: true
  # size of images for each device
  BATCH_IMAGES: 1
  # RPN proposal
  CXX_PROPOSAL: true
  RPN_NMS_THRESH: 0.7
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
  RPN_MIN_SIZE: 10
  # RPN generate proposal
  PROPOSAL_NMS_THRESH: 0.7
  PROPOSAL_PRE_NMS_TOP_N: 6000
  PROPOSAL_POST_NMS_TOP_N: 1000
  PROPOSAL_MIN_SIZE: 10
  # RCNN nms
  NMS: 0.3
  test_epoch: 40
  max_per_image: 1000

  save_img_path: './media'
